### PR TITLE
Changed method building to camel case.

### PR DESCRIPTION
**Pull request by FLYBYME**
What do you think about doing camel case?

### CODE REVIEW

**Comment by deoxxa** [comment]
I'd be perfectly happy with camleCase in addition to snake_case - best of both worlds!

**Comment by FLYBYME** [comment]
I've updated the code. This should work. But its kinda odd to have both.

**Comment by deoxxa** [comment]
I'm going to close this without merging, as it turned out looking completely different after I cleaned it up to be a bit easier to understand.

**Comment by deoxxa** [comment]
To clarify, though, I have implemented this feature.

**Comment by ghost** [comment]
@deoxxa be still, my beating heart.

**Pull request closed without merging**
